dist: xenial
language: python
python:
  - pypy3.5-6.0
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
install:
  - pip install coveralls
script:
  - coverage run --source=jsonmerge setup.py test
after_success:
  - coveralls
