name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - name: 3.7
            toxenv: py37-jsonschemalatest
          - name: 3.8
            toxenv: py38-jsonschemalatest
          - name: 3.9
            toxenv: py39-jsonschemalatest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version.name }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version.name }}
    - name: Install tox
      run: python -m pip install tox
    - name: Run tox
      run: python -m tox -e "${{ matrix.python-version.toxenv }}"
